version: "3"

networks:
  masters:
    external: true

services:
  ms-1:
    image: ms-1
    build:
      context: ms-1
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "80:80"
    networks:
      - masters